{
 "title": "Pizza Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Logging",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "totalLogins_total", "legendFormat": "success" },
    { "expr": "failedLogins_total", "legendFormat": "failure" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Users" } },
   "targets": [
    {
     "expr": "activeUsers{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "Total HTTP Requests sent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "requestsByMethod{service_name=\"jwt-pizza-service\"}",
     "legendFormat": "{{method}}"
    },
    { "expr": "totalRequests_total", "legendFormat": "all" }
   ]
  },
  {
   "title": "CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpuUsage", "legendFormat": "CPU Usage" },
    { "expr": "memoryUsage", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(totalLatency_total[5m])) / (sum(rate(totalPurchases_total[5m])) * 60)",
     "legendFormat": "Pizza Latency"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Pizzas" } },
   "targets": [
    {
     "expr": "sum(rate(totalPizzas_total[5m])) * 60",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "sum(rate(failedPurchases_total[5m])) * 60",
     "legendFormat": "Purchase Failures"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(totalLatency_total[5m])) / sum(rate(totalRequests_total[5m]))",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(totalPrice_total[5m])) * 60",
     "legendFormat": "Revenue"
    }
   ]
  }
 ]
}